/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    GpaTable: typeof import('../packages/antdv-components/src/index')['GpaTable'];
    GpaTime: typeof import('../packages/antdv-components/src/index')['GpaTime'];
  }
}
