import 'ant-design-vue/es/table/style/index.js';
import 'ant-design-vue/es/divider/style/index.js';
import 'ant-design-vue/es/checkbox/style/index.js';
import 'ant-design-vue/es/popover/style/index.js';
import 'ant-design-vue/es/tooltip/style/index.js';
import 'ant-design-vue/es/space/style/index.js';
import 'ant-design-vue/es/dropdown/style/index.js';
import 'ant-design-vue/es/menu/style/index.js';
import './index.less';
